services:
  honeypot:
    build: .
    container_name: php-honeypot
    user: "111:112" # server user and group id
    restart: unless-stopped
    networks:
      - hpnet
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    pids_limit: 128
    init: true
    volumes:
      - /srv/honeypot-v1/service/honeypot_host_logs/honeypot.log:/var/log/honeypot.log:rw
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-honeypot
    depends_on:
      - honeypot
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/honeypot.conf:/etc/nginx/conf.d/honeypot.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx:rw
    restart: unless-stopped
    networks:
      - hpnet
      - edge
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    pids_limit: 128
    init: true

networks:
  hpnet:
    driver: bridge
    internal: true
  edge:
    driver: bridge
