name: Deploy Honeypot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Hetzner
    runs-on: self-hosted
    env:
      HOME: /opt/actions-runner
      GIT_CONFIG_GLOBAL: /opt/actions-runner/.gitconfig

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Environment info
        run: |
          echo "Runner: $(hostname)"
          echo "HOME: $HOME"
          docker --version
          docker compose version || true
          systemctl --version | head -1

      - name: Build image
        run: docker build -t honeypot:latest .

      - name: Sync files
        run: |
          rsync -a --delete-after --ignore-errors \
            ./ /srv/honeypot/service/ \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'README.md'
          chown -R honeypot:honeypot /srv/honeypot/service

      - name: Restart honeypot service
        run: |
          systemctl restart honeypot
          sleep 3
          systemctl status honeypot --no-pager -l || true

      - name: Verify running containers
        run: docker ps