name: Deploy Honeypot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Hetzner
    runs-on: self-hosted
    env:
      HOME: /opt/actions-runner
      GIT_CONFIG_GLOBAL: /opt/actions-runner/.gitconfig

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Verify environment
      - name: Environment info
        run: |
          echo "Runner: $(hostname)"
          docker --version
          docker compose version || true
          systemctl --version | head -1
          echo "HOME is set to $HOME"

      # 3. Build Docker image locally
      - name: Build image
        run: |
          docker build -t honeypot:latest .

      # 4. Sync service files to /srv/honeypot/service
      - name: Sync files
        run: |
          sudo rsync -a --delete \
            ./ /srv/honeypot/service/ \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'README.md'
          sudo chown -R honeypot:honeypot /srv/honeypot/service

      # 5. Restart systemd service
      - name: Restart honeypot service
        run: |
          sudo systemctl restart honeypot
          sleep 3
          sudo systemctl status honeypot --no-pager -l || true

      # 6. Verify active containers
      - name: Verify running containers
        run: |
          echo "Active containers:"
          sudo docker ps