name: Deploy Honeypot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Hetzner
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment info
        run: |
          echo "Runner: $(hostname)"
          docker --version
          docker compose version || true
          systemctl --version | head -1

      - name: Build image
        run: |
          docker build -t honeypot:latest .

      - name: Sync files
        run: |
          sudo rsync -a --delete \
            ./ /srv/honeypot/service/ \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'README.md'
          sudo chown -R honeypot:honeypot /srv/honeypot/service

      - name: Restart service
        run: |
          sudo systemctl restart honeypot
          sleep 3
          sudo systemctl status honeypot --no-pager -l || true

      - name: Verify containers
        run: |
          sudo docker ps